services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "5000"
    command: python app.py

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/server.crt:/etc/nginx/server.crt:ro
      - ./nginx/certs/server.key:/etc/nginx/server.key:ro
      - ./nginx/certs/ca.crt:/etc/nginx/ca.crt:ro
    ports:
      - "80:80"
      - "443:443"
